### PR TITLE
jingyu

### PR DESCRIPTION
**Pull request by ShellyCode**

### CODE REVIEW

**Comment by BUPT-AC** [comment]
Please following the [NAMING RULE](https://github.com/BUPT-AC/AP/blob/master/README.md) for src code (在任务提交方式的代码部分)

**Comment by ShellyCode** [comment]
rename

**Comment by BUPT-AC** [comment]
1. Knapsack.py --> [Knapsack01.py](https://github.com/BUPT-AC/AP/blob/master/workplace/prob/20150618/Knapsack01.md)
2. RobberI.py --> [Robber_I.py](https://github.com/BUPT-AC/AP/blob/master/workplace/prob/20150618/Robber_I.md)
3. RobberII.py -->[Robber_II.py](https://github.com/BUPT-AC/AP/blob/master/workplace/prob/20150618/Robber_II.md)

**Comment by ShellyCode** [comment]
rename

**Pull request merged**
